@hostName = http://localhost:8080

@var1=value1 

# @name get_bankdownload
GET {{hostName}}/bankdownloads/email?receiver=vivekjadhav@yahoo.com&keyword=Bank Downloads
Content-Type: application/json

############################################################################################
# @name get_bankdownload
GET {{hostName}}/bankdownloads
Content-Type: application/json
############################################################################################
# @name get_bankdownload
GET {{hostName}}/search/bankdownloads?bankdownload_name=Y&start_date=1990-12-31
Content-Type: application/json

############################################################################################
GET {{hostName}}/bankdownloads/pkey?bankdownload_group=A01-Revenue&bankdownload_type=Rev-Interest
Content-Type: application/json    


############################################################################################
# @name post_bankdownloads
POST {{hostName}}/bankdownloads
Content-Type: application/json


{
    "bankdownloads": [
        {
            "bank_account_key": "104Meadow",
            "tdate": "2021-01-01",
            "description": "AC Repair",
            "amount": -100.00,
            "classification": "Clean",
            "period_status": "Closed",
            "bankdownload_group": "A02 - Expense",
            "bankdownload_type": "Exp-Repair",
            "vendor": "W9-ADELINA",
            "customer": "NA",
            "comments": "AC Repair",
            "vendor_no_w9": "AC Repair",
            "customer_no_w9": "NA"
    },
        {
            "bank_account_key": "104Meadow",
            "tdate": "2021-01-02",
            "description": "Toilet Repair",
            "amount": -100.00,
            "classification": "Clean",
            "period_status": "Closed",
            "bankdownload_group": "A02 - Expense",
            "bankdownload_type": "Exp-Repair",
            "vendor": "W9-DANNY",
            "customer": "NA",
            "comments": "Plumbing Repair",
            "vendor_no_w9": "Plumbing Repair",
            "customer_no_w9": "NA"
    },
        {
            "bank_account_key": "104Meadow",
            "tdate": "2022-01-02",
            "description": "Security Deposit",
            "amount": 1100.20,
            "classification": "Clean",
            "period_status": "Closed",
            "bankdownload_group": "A07 - Security Deposit",
            "bankdownload_type": "Liab-Security",
            "vendor": "NA",
            "customer": "NA",
            "comments": "Security Deposit",
            "vendor_no_w9": "NA",
            "customer_no_w9": "Security Deposit"
    }
    ]
}

############################################################################################
# @name delete_bankdownloads
DELETE {{hostName}}/bankdownloadsdel
Content-Type: application/json


{
    "bankdownloadsDel": [
        {
            "bank_account_key": "104Meadow",
            "tdate": "2022-01-02",
            "description": "Security Deposit",
            "amount": 1100.20
        },
        {
            "bank_account_key": "104Mead",
            "tdate": "2022-01-02",
            "description": "Security Deposit",
            "amount": 1100.20
        },
        {
            "bank_account_key": "104Meado",
            "tdate": "2022-01-02",
            "description": "Security Deposit",
            "amount": 1100.20
        }
    ]
}
############################################################################################

