@hostName = http://localhost:8080

@var1=value1 

# @name get_transaction
GET {{hostName}}/bankaccounts/email?receiver=vivekjadhav@yahoo.com&keyword=Bank Accounts
Content-Type: application/json

############################################################################################
# @name get_transaction
GET {{hostName}}/bankaccounts
Content-Type: application/json
############################################################################################
# @name get_transaction
GET {{hostName}}/search/bankaccounts?bankaccount_name=Y&start_date=1990-12-31
Content-Type: application/json

############################################################################################
GET {{hostName}}/bankaccounts/pkey?bank_account_key=Dummy
Content-Type: application/json    


############################################################################################
# @name post_transactions
POST {{hostName}}/bankaccounts
Content-Type: application/json


{
    "bankaccounts": [
        {
            "bank_account_key": "2224Heatherton",
            "bank": "Wells Fargo",
            "account_type": "Checking",
            "account_number": "999999999",
            "llc": "MDW",
            "property_name": "2224Heatherton"
        },
        {
            "bank_account_key": "4920BrianHill",
            "bank": "Wells Fargo",
            "account_type": "Checking",
            "account_number": "2123710218",
            "llc": "MDW",
            "property_name": "14920BrianHill"
        }
    ]
}

############################################################################################
# @name delete_bankaccounts
DELETE {{hostName}}/bankaccountsdel
Content-Type: application/json


{
    "bankaccountsDel": [
        {
            "bank_account_key": "Chase"
        },
        {
            "bank_account_key": "Dummy"
        },
        {
            "bank_account_key": "Vivek"
        }
    ]
}
############################################################################################

