@hostName = http://localhost:8080

@var1=value1 
    
############################################################################################
# @name post_transactions
POST {{hostName}}/birds
Content-Type: application/json


{
    "birds": [
        {
            "sender": "guppydove@gmail.com",
            "pwd": "Neer@j01"
        }
    ]
}

############################################################################################
# @name delete_llcs
DELETE {{hostName}}/llcsdel
Content-Type: application/json


{
    "llcs": [
        {
            "llc": "MID"
        },
        {
            "llc": "MDW"
        }
    ]
}
############################################################################################

