@hostName = http://localhost:8080

@var1=value1 

# @name get_transaction
GET {{hostName}}/llcs/email?receiver=vivekjadhav@yahoo.com
Content-Type: application/json

############################################################################################
# @name get_transaction
GET {{hostName}}/llcs
Content-Type: application/json
############################################################################################
# @name get_transaction
GET {{hostName}}/search/llcs?llc_name=Y&start_date=1990-12-31
Content-Type: application/json

############################################################################################
GET {{hostName}}/llcs/pkey?llc_name=MID
Content-Type: application/json    


############################################################################################
# @name post_transactions
POST {{hostName}}/llcs
Content-Type: application/json


{
    "llcs": [
        {
            "llc": "NV",
            "ein": "Neeraj Vivek",
            "llc_address": "8700 STONEBROOK PKWY UNIT 2758 FRISCO, TX 75034 CHIV",
            "llc_description": "Neeraj Vivek Partnership",
            "formation_date": "2013-10-01"
        },
        {
            "llc": "GOL",
            "ein": "87-1462999 VIV",
            "llc_address": "8700 TEST PKWY UNIT 2758 FRISCO, TX 75034 VIV",
            "llc_description": "TEST INN LLC VIV",
            "formation_date": "2022-06-29"
        },
        {
            "llc": "YYY",
            "ein": "87-1462999 PPP",
            "llc_address": "XXX TEST PKWY UNIT 2758 FRISCO, TX 75034 PPP",
            "llc_description": "XXXTEST INN LLC PPP",
            "formation_date": "2019-06-29"
        }
    ]
}

############################################################################################
# @name delete_llcs
DELETE {{hostName}}/llcsdel
Content-Type: application/json


{
    "llcsDel": [
        {
            "llc": "NV"
        },
        {
            "llc": "GOL"
        },
        {
            "llc": "YYY"
        }
    ]
}
############################################################################################

