@hostName = http://localhost:8080

@var1=value1 

# @name get_transaction
GET {{hostName}}/partners/email?receiver=vivekjadhav@yahoo.com&keyword=Partners
Content-Type: application/json

############################################################################################
# @name get_transaction
GET {{hostName}}/partners
Content-Type: application/json
############################################################################################
# @name get_transaction
GET {{hostName}}/search/partners?partner=Y&start_date=1990-12-31
Content-Type: application/json

############################################################################################
GET {{hostName}}/partners/pkey?partner=W9-CCC_SERVICES
Content-Type: application/json    


############################################################################################
# @name post_transactions
POST {{hostName}}/partners
Content-Type: application/json


{
    "partners": [
        {
            "partner" : "NA",
            "recipient_type" : "Business",
            "recipient_tin_type" : "EIN",
            "recipient_tin" : "99-999-999",
            "last_name" : "Not Applicable",
            "first_name" : "Not Applicable",
            "address" : "Not Applicable",
            "city" : "Not Applicable",
            "state" : "NA",
            "zip_code" : "99999",
            "country" : "USA"
        },
        {
            "partner" : "W9-BBB_SERVICES",
            "recipient_type" : "Business",
            "recipient_tin_type" : "EIN",
            "recipient_tin" : "99-3999953",
            "last_name" : "AAA SERVICES",
            "first_name" : "AAA SERVICES",
            "address" : "8798 SouthBall Dr ",
            "city" : "Tijuana",
            "state" : "TX",
            "zip_code" : "75098",
            "country" : "USA"
        },
        {
            "partner" : "W9-CCC_SERVICES",
            "recipient_type" : "Business",
            "recipient_tin_type" : "EIN",
            "recipient_tin" : "99-3999953",
            "last_name" : "AAA SERVICES",
            "first_name" : "AAA SERVICES",
            "address" : "8798 SouthBall Dr ",
            "city" : "Tijuana",
            "state" : "TX",
            "zip_code" : "75098",
            "country" : "USA"
        }
    ]
}

############################################################################################
# @name delete_partners
DELETE {{hostName}}/partnersdel
Content-Type: application/json


{
    "partnersDel": [
        {
            "partner": "W9-IPINA ANGEL"
        },
        {
            "partner": "W9-VALENTINE DIAZ"
        },
        {
            "partner": "W9-JOSE LANDSCAPE"
        }
    ]
}
############################################################################################

