@hostName = http://localhost:8080

@var1=value1 

# @name get_transaction
GET {{hostName}}/propertyMasters/email?receiver=vivekjadhava@yahoo.com
Content-Type: application/json

############################################################################################
# @name get_transaction
GET {{hostName}}/propertyMasters
Content-Type: application/json
############################################################################################
# @name get_transaction
GET {{hostName}}/search/propertyMasters?propertyMaster_name=Y&start_date=1990-12-31
Content-Type: application/json

############################################################################################
GET {{hostName}}/propertyMasters/pkey?property_name=104Meadow
Content-Type: application/json    


############################################################################################
# @name post_transactions
POST {{hostName}}/propertyMasters?update=X
Content-Type: application/json


{
    "propertyMasters": [
        {
            "property_name": "104Meadow",
            "property_description": "104 Meadow View Lane Anna TX 75409",
            "llc": "MDW",
            "note": "VJ",
            "purchase_date": "2013-10-29",
            "purchase_price": 122197,
            "units": 1,
            "county": "Collin"
    }
    ]
}

############################################################################################
# @name delete_propertyMasters
DELETE {{hostName}}/propertyMastersdel
Content-Type: application/json


{
    "propertyMastersDel": [
        {
            "property_name": "NVPartnership" 
        },
        {
            "property_name": "10Meadow" 
        },
        {
            "property_name": "108Meadow" 
        }
    ]
}
############################################################################################

