@hostName = http://localhost:8080

@var1=value1 

# @name get_transaction
GET {{hostName}}/propertyMasters/email?receiver=vivekjadhav@yahoo.com&keyword=Property Master
Content-Type: application/json

############################################################################################
# @name get_transaction
GET {{hostName}}/propertyMasters
Content-Type: application/json
############################################################################################
# @name get_transaction
GET {{hostName}}/search/propertyMasters?propertyMaster_name=Y&start_date=1990-12-31
Content-Type: application/json

############################################################################################
GET {{hostName}}/propertyMasters/pkey?property_name=2224Heatherton
Content-Type: application/json    


############################################################################################
# @name post_transactions
POST {{hostName}}/propertyMasters?update=X
Content-Type: application/json


{
    "propertyMasters": [
        {
            "property_name": "2224Heatherton",
            "property_description": "2224 Heatherton Place Plano TX 75023",
            "llc": "PAG",
            "note": "LLC",
            "purchase_date": "2020-05-05",
            "sell_date": "2021-04-20",
            "purchase_price": 198000,
            "sell_price": 290000,
            "units": 1,
            "county": "Collin"
    }
    ]
}

############################################################################################
# @name delete_propertyMasters
DELETE {{hostName}}/propertyMastersdel
Content-Type: application/json


{
    "propertyMastersDel": [
        {
            "property_name": "NVPartnership" 
        },
        {
            "property_name": "10Meadow" 
        },
        {
            "property_name": "108Meadow" 
        }
    ]
}
############################################################################################

