"""Add llc_description and formation_date columns

Revision ID: 3ef50c3ceb8a
Revises: 38fe36c5f950
Create Date: 2024-04-20 09:10:04.025456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ef50c3ceb8a'
down_revision: Union[str, None] = '38fe36c5f950'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
    # Instructions for upgrading the database
    op.add_column('llcs', sa.Column('llc_description', sa.String(), nullable=True))
    op.add_column('llcs', sa.Column('formation_date', sa.Date(), nullable=True))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
        # ### end Alembic commands ###
    # Instructions for downgrading the database
    op.drop_column('llcs', 'formation_date')
    op.drop_column('llcs', 'llc_description')