"""Create transaction_types_master

Revision ID: a3785600ad21
Revises: bf167da079d9
Create Date: 2024-04-16 11:39:45.646874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3785600ad21'
down_revision: Union[str, None] = 'bf167da079d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transaction_types',
    sa.Column('id', sa.INTEGER(), primary_key=True, autoincrement=True, nullable=False),
    sa.Column('transaction_group', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('transaction_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('transaction_description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name = 'transaction_types_pkey'),
    sa.UniqueConstraint('transaction_group','transaction_type', name='uix_transaction_type_group') 
    )
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.drop_table('transaction_types')
    # ### end Alembic commands ###
