"""Create llc_master

Revision ID: bf167da079d9
Revises: f93cd9c20425
Create Date: 2024-04-16 08:46:16.969955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf167da079d9'
down_revision: Union[str, None] = 'f93cd9c20425'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llc_master',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('property_master_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('llc', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('ein', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('llc_address', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='llc_master_pkey'),
    sa.UniqueConstraint('llc', name='llc_master_llc_key'),
    postgresql_ignore_search_path=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('llc_master')
    # ### end Alembic commands ###
