"""Added PropertyMaster table

Revision ID: ed25f63739e1
Revises: 112c2833dc69
Create Date: 2024-04-14 21:07:05.225492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed25f63739e1'
down_revision: Union[str, None] = '112c2833dc69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('property_master',
                    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
                    sa.Column('property_name', sa.VARCHAR(), autoincrement=False, nullable=False),
                    sa.Column('property_description', sa.VARCHAR(), autoincrement=False, nullable=True),
                    sa.Column('LLC', sa.VARCHAR(), autoincrement=False, nullable=True),
                    sa.Column('note', sa.VARCHAR(), autoincrement=False, nullable=True),
                    sa.Column('account_type', sa.VARCHAR(), autoincrement=False, nullable=True),
                    sa.Column('bank_name', sa.VARCHAR(), autoincrement=False, nullable=True),
                    sa.Column('account_number', sa.NUMERIC(precision=10, scale=0), autoincrement=False, nullable=True),
                    sa.PrimaryKeyConstraint('id', name='property_master_pkey'),
                    sa.UniqueConstraint('property_name', name='property_master_property_name_key')
                    )
    
    op.execute(
        """
        ALTER TABLE transactions
        ADD CONSTRAINT fk_property_name
        FOREIGN KEY (property_name)
        REFERENCES property_master(property_name)
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('property_master')
    op.drop_constraint('fk_property_name', 'transactions', type_='foreignkey')
    # ### end Alembic commands ###
