"""Added Check Contraints for note and account_type

Revision ID: f8868401eda1
Revises: ed25f63739e1
Create Date: 2024-04-14 21:34:38.172135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8868401eda1'
down_revision: Union[str, None] = 'ed25f63739e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Adding a CHECK constraint
    op.execute(
        """
        ALTER TABLE "property_master"
        ADD CONSTRAINT "ck_PropertyMaster_note"
        CHECK ("note" IN ('LLC','VJ','NG','PG'))
        """
    )
    op.execute(
        """
        ALTER TABLE "property_master"
        ADD CONSTRAINT "ck_PropertyMaster_account_type"
        CHECK ("account_type" IN ('Checking','Savings'))
        """
    )
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        ALTER TABLE "property_master"
        DROP CONSTRAINT "ck_PropertyMaster_note"
        """
    )
    op.execute(
        """
        ALTER TABLE "property_master"
        DROP CONSTRAINT "ck_PropertyMaster_account_type"
        """
    )
    # ### end Alembic commands ###
