"""Change property_master.LLC to property_master.llc

Revision ID: f93cd9c20425
Revises: f8868401eda1
Create Date: 2024-04-16 08:39:05.391334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f93cd9c20425'
down_revision: Union[str, None] = 'f8868401eda1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Renaming column 'LLC' to 'llc' in 'property_master' table
    op.alter_column('property_master', 'LLC', new_column_name='llc')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Renaming column 'llc' to 'LLC' in 'property_master' table
    op.alter_column('property_master', 'llc', new_column_name='LLC')
    # ### end Alembic commands ###
